# Problem 2 - Peter Bizouaks - Python version: 3.12
'''Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:1,2,3,5,8,13,21,34,55,89, …
By considering the terms in the Fibonacci sequence whose last value does not exceed 100,000,
 find the sum of the even-valued terms.  You will be providing the evaluator with clear instructions 
 on how to accept the input in a separate readme file with problem no.

'''
# First two terms of the Fibonacci sequence
x = 1
y = 2

# Initialize even_sum variable to hold sum of even terms
even_sum = 0

# Loop through Fibonacci numbers while the values do not exceed 100,000
while x <= 100000:
    # If the term is even, add it to the sum
    if x % 2 == 0:
        even_sum += x
    #  next Fibonacci number
    y, x = x, y + x

# Output the sum of even-valued terms
print("Sum of even-valued terms:", even_sum)
