# Problem 2
'''Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:1,2,3,5,8,13,21,34,55,89, …
By considering the terms in the Fibonacci sequence whose last value does not exceed 100,000,
 find the sum of the even-valued terms.  You will be providing the evaluator with clear instructions 
 on how to accept the input in a separate readme file with problem no.

'''
import numpy as np

